name: Test Predicate

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.2"

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test